config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  #routes.rb

  resources :artigos

  root 'artigos#index' #artigos controller com a acao index que esta em controller/artigos_controller
  get 'sobre' => 'artigos#sobre'


end

app/models/artigo.rb
class Artigo < ActiveRecord::Base

	belongs_to :usuario
	belongs_to :categoria


end

app/models/categoria.rb
class Categoria < ActiveRecord::Base

	has_many :artigos

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :artigos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artigos_controller.rb
class ArtigosController < ApplicationController
	before_action :achar_artigo, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_usuario!, except: [:index, :show]
	#se usuario quiser entrar ele nao ser redirecionado para o sign up
	def index
		if params[:categoria].blank?
			@artigos = Artigo.all.order("created_at DESC")
		else
			@categoria_id = Categoria.find_by(nome: params[:categoria]).id
			@artigos = Artigo.where(categoria_id: @categoria_id).order("created_at DESC")
		end


	end
	#se nao estiver selecionado um artigo, ira listar todos
	#se nao, ira listar apenas daquela categoria

	def show
	end
	

	def new
		@artigo = current_usuario.artigos.build
	end

	def create
		@artigo = current_usuario.artigos.build(artigo_parametros)
		if @artigo.save
			redirect_to @artigo
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @artigo.update(artigo_parametros)
			redirect_to @artigo
		else
			render 'edit'
		end
	end

	def destroy
		@artigo.destroy
		redirect_to root_path
	end

	def sobre
	end


	private

	def artigo_parametros
		params.require(:artigo).permit(:Título, :Conteúdo, :categoria_id)
	end

	def achar_artigo
		@artigo = Artigo.find(params[:id])
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artigos_helper.rb
module ArtigosHelper
end

app/views/artigos/_form.html.haml
%br

= simple_form_for @artigo do |f|
	%blockquote
		= f.collection_select :categoria_id, Categoria.all, :id, :Nome, { promt: "Selecione uma Categoria" }
	
	
	%blockquote
		= f.input :Título
	
	%blockquote
		= f.input :Conteúdo
	
	%blockquote
		= f.submit

	
	/o barra e comentario em haml, obs: se deixar sem o igual vira um print normal

app/views/artigos/edit.html.haml
%img(src="http://imageshack.com/a/img908/2835/M5lwNo.png" align="center" height="100" widith="100")

%h1(align="center") Editar Artigo

= render 'form'

%br
%p(align="center")
	= link_to "Voltar", root_path
%br
%br
%br
%br
%br
%br
%br
%br
%br
%br
%img(src="http://imageshack.com/a/img905/5237/rFUJuH.png" align="left")

app/views/artigos/index.html.haml
%img(src="http://imageshack.com/a/img908/2835/M5lwNo.png" align="center" height="100" widith="100")
/%p(class="navbar-text")
/	Signed in as Mark Otto

%body(bgcolor="#FFFFFF")
%h2(align ="center") Discipule - Cadastro de Conteúdos Online

%br

- if usuario_signed_in?
	%b
		%blockquote
			%p(align="right")
				=link_to('Sair', destroy_usuario_session_path, :method => :delete)

		%br

		%p(align="center")
			=link_to "Clique aqui para adicionar um conteúdo", new_artigo_path
		%br
 
- else
	%b
		%blockquote
			%p(align="right")
				=link_to('Entrar', new_usuario_session_path)
			
		%br

- @artigos.each do |artigo|
	%blockquote
		%h2
			= link_to artigo.Título, artigo
	%blockquote
		%p 
			= truncate(artigo.Conteúdo, length: 140)
	%blockquote
		%p(align="right")
			Publicado em 
			= artigo.created_at.strftime('%d %b de %Y')



%br
%br
%hr(bgcolor="#00000A")
%br
%b
	%blockquote
		%p(align="left")
			=link_to "Sobre o Discipule", "sobre"



%img(src="http://imageshack.com/a/img905/5237/rFUJuH.png" align="left")

app/views/artigos/new.html.haml
%img(src="http://imageshack.com/a/img908/2835/M5lwNo.png" align="center" height="100" widith="100")

%h1(align="center") Novo Conteúdo


= render 'form'

%br
%p(align="center")
	= link_to "Voltar", root_path


%br
%br
%img(src="http://imageshack.com/a/img905/5237/rFUJuH.png" align="left")

app/views/artigos/show.html.haml
%img(src="http://imageshack.com/a/img908/2835/M5lwNo.png" align="center" height="100" widith="100")

%blockquote

	%h1= @artigo.Título
	%p= @artigo.Conteúdo

%blockquote

	= link_to "Editar", edit_artigo_path(@artigo)

	= link_to "Deletar", artigo_path(@artigo), method: :delete
	
%br
%p(align="center")
	= link_to "Voltar", root_path


%br
%br
%img(src="http://imageshack.com/a/img905/5237/rFUJuH.png" align="left")

app/views/artigos/sobre.html.haml
%img(src="http://imageshack.com/a/img908/2835/M5lwNo.png" align="center" height="100" widith="100")

%h1(align="center") Sobre

%p(align="center")
	Universidade de Brasília
	%br
	Faculdade UnB Gama
	%br
	Engenharia de Software
	%br
	Orientação a Objetos
	%br
	Professor: Renato Coral
	%br
	%br

	Projeto: Discipule - Cadastro de Conteúdos Online
	%br
	Alunos: Eduardo Gomes, Miguel Pimentel, Daniel Moura
	%br
	%br
	Criado em
	%br
	09 de Dezembro de 2015



%p(align="center")
	= link_to "Voltar", root_path
%br
%br
%img(src="http://imageshack.com/a/img905/5237/rFUJuH.png" align="left")

app/views/layouts/application.html.haml
!!!
%html
%head

	%title Discipule
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags #identacao aqui teve erro, resolvido com backspace ate true da linha anterior + enter

%body(id="params[:controller].parameterize %>_controller")
	%p.notice 
		= notice
	%p.alert 
		= alert

	=link_to "Todos Conteúdos", root_path

	- Categoria.all.each do |categoria|
		= link_to categoria.Nome, artigos_path(categoria: categoria.Nome)

	=yield


	